### ISSUE TITLE
opam: required argument PACKAGES is missing

### ISSUE THREAD

**Issue by humazahid332** [jubnzv/iec-checker#12] opened 2022-08-12 06:03 UTC
I am trying to install the IEC checker on ubuntu. As mentioned, I installed Opam first by following the instructions from [https://ocaml.org/docs/install.html] Installation is done successfully. Screenshots are attached. 
![WhatsApp Image 2022-08-12 at 10 40 07 AM](https://user-images.githubusercontent.com/110456187/184293635-e46414f1-e614-4c71-9488-53c43d16c014.jpeg)

![WhatsApp Image 2022-08-12 at 10 42 37 AM](https://user-images.githubusercontent.com/110456187/184293668-d0a077fc-ec7d-46d1-9003-b20aa6581f97.jpeg)

![WhatsApp Image 2022-08-12 at 10 43 39 AM](https://user-images.githubusercontent.com/110456187/184293717-fef7a015-7a67-489a-89cf-ff051525715c.jpeg)
After successful installation when I run the command 
`opam install --deps-only . ` to install the dependencies. It says the required argument PACKAGES is missing. Please help me resolve this issue. 
![WhatsApp Image 2022-08-12 at 10 44 22 AM](https://user-images.githubusercontent.com/110456187/184293937-753df949-8090-427f-9c88-b2f3bfef9c62.jpeg)

**Comment by jubnzv** [comment] 2022-08-12 06:18
Hi @humazahid332,

The first command `opam install --deps-only .` successfully finished. It says that you already have all the required packages.

Next, when you execute `opam install --deps-only` (without dot `.`), `opam` asks you to provide package you want to install. This command is incorrect, you don't need it.

So you can continue to build the package with `dune` according to the README.

**Comment by humazahid332** [comment] 2022-08-12 06:34
How to install the IEC checker now. I am executing the next command in the readme but it gives an error.
![WhatsApp Image 2022-08-12 at 11 32 48 AM](https://user-images.githubusercontent.com/110456187/184297676-a3d7cbf2-3284-4afd-a2ec-01438d737ae8.jpeg)

**Comment by jubnzv** [comment] 2022-08-12 07:03
> How to install the IEC checker now. I am executing the next command in the readme but it gives an error.

`cd` to the project directory.

**Comment by jubnzv** [comment] 2022-08-12 07:13
Well, I understood. You didn't clone the repository.

OK, when you're building a project from the source code, first you need to get the sources, right? So, execute the following command:

```
git clone https://github.com/jubnzv/iec-checker
```

This command downloads the source code of `iec-checker` to your machine using [`git`](https://git-scm.com/docs/git). Then you should [`cd`](https://man7.org/linux/man-pages/man1/cd.1p.html) to the downloaded directory:

```
cd iec-checker
```

And then you should just execute commands from the README file:

```
opam install --deps-only .
dune build @install
mkdir output
dune install --prefix ./output
```

Please note that these are things that every developer should know. I suggest you to read the [Git book](https://git-scm.com/book/en/v2) and some introduction to the unix-like systems.

Also, if building from the source code is hard, feel free to download pre-built binaries from the release page: https://github.com/jubnzv/iec-checker/releases/tag/v0.4.

**Comment by jubnzv** [comment] 2022-08-13 11:13
I close this, since I think that the issue is solved. Feel free to re-open it, if you have any other questions.

**Closed by jubnzv** 2022-08-13 11:13 UTC
